# Generated by Django 2.1.3 on 2018-11-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModelField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField(editable=False)),
                ('field_id', models.PositiveIntegerField(editable=False)),
                ('null', models.BooleanField(default=True)),
                ('unique', models.BooleanField(default=False)),
                ('max_length', models.PositiveIntegerField(null=True)),
                ('field_content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='field_content_types', to='contenttypes.ContentType')),
                ('model_content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='model_content_types', to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dynamicmodelfield',
            unique_together={('model_content_type', 'model_id', 'field_content_type', 'field_id')},
        ),
    ]
