# Generated by Django 2.1.3 on 2018-12-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFieldSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField()),
                ('field_id', models.PositiveIntegerField()),
                ('null', models.BooleanField(default=True)),
                ('unique', models.BooleanField(default=False)),
                ('max_length', models.PositiveIntegerField(null=True)),
                ('field_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('model_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_field_columns', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
