# Generated by Django 3.1.1 on 2020-09-21 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelschema',
            name='_modified',
        ),
    ]
