# Generated by Django 2.2.24 on 2022-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_remove_modelschema__modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldschema',
            name='db_name',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='modelschema',
            name='db_name',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
