# Generated by Django 2.2.24 on 2022-04-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_add_classname_remove_datatype'),
        ('dynamic_models', '0003_auto_20220427_1058'),
    ]

    operations = [
    ]
