# Generated by Django 2.2.24 on 2022-05-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_merge_20220427_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldschema',
            name='db_name',
        ),
    ]
