# Generated by Django 3.2.13 on 2022-06-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_modelschema_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelschema',
            name='is_managed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modelschema',
            name='use_applable_as_table_prefix',
            field=models.BooleanField(default=True),
        ),
    ]
