# Generated by Django 3.2.13 on 2022-06-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_modelschema_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelschema',
            name='managed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modelschema',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='modelschema',
            name='db_table_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='modelschema',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
