# Generated by Django 3.2.13 on 2022-06-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0005_auto_20220621_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelschema',
            name='db_table_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
