# Generated by Django 2.2.24 on 2022-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0005_remove_fieldschema_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelschema',
            name='db_name',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
