# Generated by Django 2.1.3 on 2018-11-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleFieldSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=32)),
                ('data_type', models.CharField(choices=[('char', 'short text'), ('text', 'long text'), ('int', 'integer'), ('float', 'float'), ('bool', 'boolean'), ('date', 'date')], editable=False, max_length=8)),
                ('normal_field', models.IntegerField()),
                ('related_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.RelatedModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleModelSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=32)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('normal_field', models.IntegerField()),
                ('related_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.RelatedModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
